
spring:
  datasource:
    url: jdbc:h2:mem:insurance;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2.console.enabled: true
